# Generated by Django 3.0.4 on 2020-06-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('terminal_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('terminal_name', models.CharField(max_length=10)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footage_app.Branch')),
            ],
        ),
    ]
