# Generated by Django 3.0.4 on 2020-06-08 01:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('footage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='branch_id',
            field=models.ForeignKey(default='XXXX', on_delete=django.db.models.deletion.SET_DEFAULT, to='footage_app.Branch'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=6)),
                ('card_pan', models.CharField(max_length=4)),
                ('amount', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('trxn_success', models.BooleanField(default=True)),
                ('terminal_id', models.ForeignKey(default='9999', on_delete=django.db.models.deletion.SET_DEFAULT, to='footage_app.Terminal')),
            ],
        ),
    ]
