# Generated by Django 3.0.4 on 2020-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage_app', '0002_auto_20200607_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='terminal_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
