# Generated by Django 3.0.4 on 2020-06-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footage_app', '0004_auto_20200610_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
